### ISSUE TITLE
Feature request: UART/serial cable

### ISSUE THREAD

**Issue by Heath123** [debrouxl/tilibs#72]
Is it possible to repurpose the link cable as a generic UART/serial (not sure what the right terminology is) cable? This would be useful for connecting it to my Casio calculator and maybe for other things as well

**Comment by debrouxl** [comment]
In libticables, the GrayLink is the closest thing to normal serial communication.
But first of all, are you using a Casio calculator model not covered by https://p7.planet-casio.com/en.html ?

**Comment by Heath123** [comment]
I don't own a Casio link cable, I was wondering if my old SilverLink TI cable could be repurposed as one, since it has the same physical connector at the end (a 2.5mm jack)

**Comment by debrouxl** [comment]
The SilverLink _might_ be repurposable as a Casio link cable, _if_ the electrical signals are compatible enough (voltage tolerance, waveforms, etc.). However, since the SilverLink's standard firmware only speaks TI's specific SilverLink protocol on the USB side and TI's half-duplex classic protocol on the proprietary 2.5mm stereo-jack-like  connector side, in order to make a SilverLink speak Casio's protocols on both sides, custom firmware and reflashing thereof looks like a hard requirement... in which case you could arguably be better off using a documented microcontroller with an open development environment: Arduino, STM32-based board, or similar :)

The fx-CG50's MSD interface is mostly a boon for users, but no standard USB protocol covers all operations which make sense on a graphing calculator, e.g. MSD is a poor fit for remote control.

**Comment by Heath123** [comment]
Oh, I hoped this library had direct enough control to make that possible, thanks for answering though

**Comment by debrouxl** [comment]
Direct bit-banging on classic DB9 and DB25 ports is what the BlackLink / "$4 cable" and ParallelLink / "$5 cable" do, but they implement TI's half-duplex protocol, not anything else. Such physical ports are getting harder and harder to find on real computers; not only many USB / RS232 adapters do not support low-level bit-banging, but a number of PCI(e) adapters do not provide the right kind of low-level access either.
With the USB ports, basically, the effective solution is a microcontroller running software speaking (some USB protocol) on the one side and (UART or arbitrary bit-banged protocol) on the other side.
